### ISSUE TITLE
data prepare

### ISSUE THREAD

**Issue by BigBuffa1o** [UARK-AICV/AOE-Net#2]
i want to reproduce the result on thumos14 dataset,however where can i find thumos_annotations_09.json file? Can you update it to github?
Also i find it diffcult to read and extract feature from my own custom dataset to form as the specific format of your tsn_env_feature,can you provide the code? Why a video has seveal json file and what does the 'segment' means on your feature json file? much thanks!

**Comment by Rui-hue** [comment]
Have you solved this problem? How was it solved? I also have questions about this.

**Comment by Rui-hue** [comment]
thumos_annotations_09 Where is the .json file?

**Comment by Rui-hue** [comment]
Where is the thumos_annotations_09 .json file?

**Comment by vhvkhoa** [comment]
Hello, sorry for my delayed response as I am working on another project right now.
I upload the file [here](https://github.com/UARK-AICV/AOE-Net/blob/9079f63f166497525483905a936dbf007e0e4017/evaluation_thumos/thumos_annotations_09.json) for your reference.
