### ISSUE TITLE
.json files

### ISSUE THREAD

**Issue by Rui-hue** [UARK-AICV/AOE-Net#6]
Can you share the code for generating feature data. json files and label data. json files? I don't know how to generate data in this format.

**Comment by vhvkhoa** [comment]
Hi Rui-hue,

I modified SlowFast source code to extract agent features and environment features. The model I used is SlowOnly+R50.
https://github.com/facebookresearch/SlowFast

Because the code is not cleaned so I didn't publish it. I saw a repo that does feature extraction on SlowFast:
https://github.com/tridivb/slowfast_feature_extractor
Maybe you'd want to use it.

**Comment by Rui-hue** [comment]
May I ask if the “segment” [0,16] “features” in env feature data refers to the segment feature of a video segment with 0-16 frames as the segment feature？

**Comment by Rui-hue** [comment]
May I ask if the “segment” [0,16] “features” in env feature data refers to the segment feature of a video segment with 0-16 frames as the segment feature？
![微信图片_20231103103946](https://github.com/UARK-AICV/AOE-Net/assets/138572643/b02c4896-b990-4a06-ac6d-da528fb6826c)

**Comment by vhvkhoa** [comment]
yes, but it was supposed to be used only for my debugging.

**Comment by 67587597** [comment]
> yes, but it was supposed to be used only for my debugging.
Hi, thank you for your work. I want to concatenate features of another modality with the environment features. I assumed that each video was segmented into 100 segments and then the features extracted for each segment, but your reply here and the method mentioned in the paper 
> divide V into a sequence of δ−frame snippets 
are a bit confusing. Did you fix the sampling rate for all segments, or you focused on producing fixed number of segments with varying sampling rate? Thank you.

**Comment by vhvkhoa** [comment]
> > yes, but it was supposed to be used only for my debugging.  >
> 
> Hi, thank you for your work. I want to concatenate features of another modality with the environment features. I assumed that each video was segmented into 100 segments and then the features extracted for each segment, but your reply here and the method mentioned in the paper
> 
> > divide V into a sequence of δ−frame snippets.  >
> 
> are a bit confusing. Did you fix the sampling rate for all segments, or you focused on producing fixed number of segments with varying sampling rate? Thank you.

I think segments and snippets in your comment are the same. Sorry for the confusion, but I should use `snippet` in the json file to be more precise.

For ActivityNet, I rescaled all videos to 1600 frames, then I extract features using SlowFast source code (SlowOnly model) with snippet size of 16. So, every video is represented by a sequence of 100 features.
