### ISSUE TITLE
missed ActivityNet-1.3 Object features link

### ISSUE THREAD

**Issue by Chaxigo** [UARK-AICV/AOE-Net#9]
[expiredlink](https://uark-my.sharepoint.com/:u:/g/personal/sangt_uark_edu/EW1wAz-z955HuZUD49yxAaQB8Rc3eOPMpkWZQ0b2LURqnA?e=jj9zSU)

**Comment by vhvkhoa** [comment]
Sorry for the late response, please check README for our new linke to object features.
